// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Primary content in *Blog Article → Slice zone → Text → Primary*
 */
export interface BlogArticleDocumentDataBodyTextSlicePrimary {
  /**
   * Text Section field in *Blog Article → Slice zone → Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].text.primary.text_section
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_section: prismic.RichTextField;
}

/**
 * Slice for *Blog Article → Slice zone*
 */
export type BlogArticleDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Simplify<BlogArticleDocumentDataBodyTextSlicePrimary>,
  never
>;

/**
 * Primary content in *Blog Article → Slice zone → Hero Title Only → Primary*
 */
export interface BlogArticleDocumentDataBodyHeroTitleOnlySlicePrimary {
  /**
   * TItle field in *Blog Article → Slice zone → Hero Title Only → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Descrition field in *Blog Article → Slice zone → Hero Title Only → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.primary.descrition
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descrition: prismic.RichTextField;

  /**
   * anchor field in *Blog Article → Slice zone → Hero Title Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Item content in *Blog Article → Slice zone → Hero Title Only → Items*
 */
export interface BlogArticleDocumentDataBodyHeroTitleOnlySliceItem {
  /**
   * Cta label field in *Blog Article → Slice zone → Hero Title Only → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.items.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta link field in *Blog Article → Slice zone → Hero Title Only → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.items.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Cta type field in *Blog Article → Slice zone → Hero Title Only → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[].hero_title_only.items.cta_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cta_type: prismic.SelectField<"Primary" | "Secondary" | "Text">;
}

/**
 * Slice for *Blog Article → Slice zone*
 */
export type BlogArticleDocumentDataBodyHeroTitleOnlySlice = prismic.Slice<
  "hero_title_only",
  Simplify<BlogArticleDocumentDataBodyHeroTitleOnlySlicePrimary>,
  Simplify<BlogArticleDocumentDataBodyHeroTitleOnlySliceItem>
>;

type BlogArticleDocumentDataBodySlice =
  | BlogArticleDocumentDataBodyTextSlice
  | BlogArticleDocumentDataBodyHeroTitleOnlySlice;

/**
 * Item in *Blog Article → Social cards*
 */
export interface BlogArticleDocumentDataSocialCardsItem {
  /**
   * Social card title field in *Blog Article → Social cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.social_cards[].social_card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_card_title: prismic.KeyTextField;

  /**
   * Social card description field in *Blog Article → Social cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.social_cards[].social_card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_card_description: prismic.KeyTextField;

  /**
   * Social card image field in *Blog Article → Social cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.social_cards[].social_card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_card_image: prismic.ImageField<never>;
}

/**
 * Content for Blog Article documents
 */
interface BlogArticleDocumentData {
  /**
   * Title field in *Blog Article*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Excerpt field in *Blog Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  excerpt: prismic.RichTextField;

  /**
   * Featured Image field in *Blog Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Category field in *Blog Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  category: prismic.ContentRelationshipField<"blog_category">;

  /**
   * Slice zone field in *Blog Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<BlogArticleDocumentDataBodySlice> /**
   * Meta title field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Blog Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Canonical link field in *Blog Article*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.canonical_link
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonical_link: prismic.LinkField;

  /**
   * Social cards field in *Blog Article*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_article.social_cards[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_cards: prismic.GroupField<
    Simplify<BlogArticleDocumentDataSocialCardsItem>
  >;
}

/**
 * Blog Article document from Prismic
 *
 * - **API ID**: `blog_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogArticleDocumentData>,
    "blog_article",
    Lang
  >;

/**
 * Content for Blog Category documents
 */
interface BlogCategoryDocumentData {
  /**
   * Category Name field in *Blog Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_category.category_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category_name: prismic.KeyTextField;
}

/**
 * Blog Category document from Prismic
 *
 * - **API ID**: `blog_category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogCategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogCategoryDocumentData>,
    "blog_category",
    Lang
  >;

/**
 * Primary content in *Home page → Slice zone → Featured Websites → Primary*
 */
export interface HomePageDocumentDataBodyFeaturedWebsitesSlicePrimary {
  /**
   * Title field in *Home page → Slice zone → Featured Websites → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].featured_websites.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Description field in *Home page → Slice zone → Featured Websites → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].featured_websites.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * anchor field in *Home page → Slice zone → Featured Websites → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].featured_websites.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Item content in *Home page → Slice zone → Featured Websites → Items*
 */
export interface HomePageDocumentDataBodyFeaturedWebsitesSliceItem {
  /**
   * Website field in *Home page → Slice zone → Featured Websites → Items*
   *
   * - **Field Type**: Integration Fields (Catalog: `slicify-legacy--prismic_websites`)
   * - **Placeholder**: Select Prismic showcased website
   * - **API ID Path**: home_page.body[].featured_websites.items.website
   * - **Documentation**: https://prismic.io/docs/field#integration
   */
  website: prismic.IntegrationField;
}

/**
 * Slice for *Home page → Slice zone*
 */
export type HomePageDocumentDataBodyFeaturedWebsitesSlice = prismic.Slice<
  "featured_websites",
  Simplify<HomePageDocumentDataBodyFeaturedWebsitesSlicePrimary>,
  Simplify<HomePageDocumentDataBodyFeaturedWebsitesSliceItem>
>;

/**
 * Primary content in *Home page → Slice zone → Text → Primary*
 */
export interface HomePageDocumentDataBodyTextSlicePrimary {
  /**
   * Title field in *Home page → Slice zone → Text → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Text Section field in *Home page → Slice zone → Text → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].text.primary.text_section
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_section: prismic.RichTextField;

  /**
   * Image field in *Home page → Slice zone → Text → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[].text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Slice for *Home page → Slice zone*
 */
export type HomePageDocumentDataBodyTextSlice = prismic.Slice<
  "text",
  Simplify<HomePageDocumentDataBodyTextSlicePrimary>,
  never
>;

type HomePageDocumentDataBodySlice =
  | HomePageDocumentDataBodyFeaturedWebsitesSlice
  | HomePageDocumentDataBodyTextSlice
  | HeroSlice;

/**
 * Item in *Home page → Social cards*
 */
export interface HomePageDocumentDataSocialCardsItem {
  /**
   * Social card title field in *Home page → Social cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.social_cards[].social_card_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_card_title: prismic.KeyTextField;

  /**
   * Social card description field in *Home page → Social cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.social_cards[].social_card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  social_card_description: prismic.KeyTextField;

  /**
   * Social card image field in *Home page → Social cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.social_cards[].social_card_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_card_image: prismic.ImageField<never>;
}

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
  /**
   * Slice zone field in *Home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.body[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  body: prismic.SliceZone<HomePageDocumentDataBodySlice> /**
   * Meta title field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta description field in *Home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Canonical link field in *Home page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.canonical_link
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  canonical_link: prismic.LinkField;

  /**
   * Social cards field in *Home page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.social_cards[]
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_cards: prismic.GroupField<
    Simplify<HomePageDocumentDataSocialCardsItem>
  >;
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes =
  | BlogArticleDocument
  | BlogCategoryDocument
  | HomePageDocument;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * TItle field in *Hero → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Descrition field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.descrition
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descrition: prismic.RichTextField;

  /**
   * anchor field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.default.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceDefaultItem {
  /**
   * Cta label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Cta type field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cta_type: prismic.SelectField<"Primary" | "Secondary" | "Text">;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  Simplify<HeroSliceDefaultItem>
>;

/**
 * Primary content in *Hero → Hero Title Only → Primary*
 */
export interface HeroSliceHeroTitleOnlyPrimary {
  /**
   * TItle field in *Hero → Hero Title Only → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.heroTitleOnly.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * anchor field in *Hero → Hero Title Only → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.heroTitleOnly.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Hero Title Only variation for Hero Slice
 *
 * - **API ID**: `heroTitleOnly`
 * - **Description**: Hero Title Only
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroTitleOnly = prismic.SharedSliceVariation<
  "heroTitleOnly",
  Simplify<HeroSliceHeroTitleOnlyPrimary>,
  never
>;

/**
 * Primary content in *Hero → Hero Blue Background → Primary*
 */
export interface HeroSliceHeroBlueBackgroundPrimary {
  /**
   * TItle field in *Hero → Hero Blue Background → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.heroBlueBackground.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Descrition field in *Hero → Hero Blue Background → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.heroBlueBackground.primary.descrition
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descrition: prismic.RichTextField;

  /**
   * anchor field in *Hero → Hero Blue Background → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.heroBlueBackground.primary.anchor
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  anchor: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHeroBlueBackgroundItem {
  /**
   * Cta label field in *Hero → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Cta link field in *Hero → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField;

  /**
   * Cta type field in *Hero → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: Hero.items[].cta_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  cta_type: prismic.SelectField<"Primary" | "Secondary" | "Text">;
}

/**
 * Hero Blue Background variation for Hero Slice
 *
 * - **API ID**: `heroBlueBackground`
 * - **Description**: Hero Blue Background
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroBlueBackground = prismic.SharedSliceVariation<
  "heroBlueBackground",
  Simplify<HeroSliceHeroBlueBackgroundPrimary>,
  Simplify<HeroSliceHeroBlueBackgroundItem>
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHeroTitleOnly
  | HeroSliceHeroBlueBackground;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `Hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"Hero", HeroSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogArticleDocument,
      BlogArticleDocumentData,
      BlogArticleDocumentDataBodyTextSlicePrimary,
      BlogArticleDocumentDataBodyHeroTitleOnlySlicePrimary,
      BlogArticleDocumentDataBodyHeroTitleOnlySliceItem,
      BlogArticleDocumentDataBodySlice,
      BlogArticleDocumentDataSocialCardsItem,
      BlogCategoryDocument,
      BlogCategoryDocumentData,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataBodyFeaturedWebsitesSlicePrimary,
      HomePageDocumentDataBodyFeaturedWebsitesSliceItem,
      HomePageDocumentDataBodyTextSlicePrimary,
      HomePageDocumentDataBodySlice,
      HomePageDocumentDataSocialCardsItem,
      AllDocumentTypes,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceDefaultItem,
      HeroSliceHeroTitleOnlyPrimary,
      HeroSliceHeroBlueBackgroundPrimary,
      HeroSliceHeroBlueBackgroundItem,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroTitleOnly,
      HeroSliceHeroBlueBackground,
    };
  }
}
